apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
data:
  MYSQL_DATABASE: cm9vdA== # base64-encoded value of "bookie"
  MYSQL_ROOT_PASSWORD: cm9vdA== # base64-encoded value of "root"
  MYSQL_PASSWORD: cm9vdA==
  MYSQL_USER: cm9vdA==
